services:
  - type: web
    name: google-token-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python token_api.py
    envVars:
      - key: PORT
        value: 8080
